---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-db-user
  namespace: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: authelia-db-user
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: postgres-authelia-user/username
    - secretKey: password
      remoteRef:
        key: postgres-authelia-user/password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-db-user
  namespace: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: grafana-db-user
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: postgres-grafana-user/username
    - secretKey: password
      remoteRef:
        key: postgres-grafana-user/password
