apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-shared
  namespace: postgres
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18

  bootstrap:
    initdb:
      database: authelia
      owner: authelia
      dataChecksums: true

  storage:
    size: 10Gi
    storageClass: longhorn

  resources:
    requests:
      cpu: '1'
      memory: 1Gi
    limits:
      cpu: '1'
      memory: 1Gi

  postgresql:
    parameters:
      password_encryption: scram-sha-256
      shared_buffers: 256MB
      max_slot_wal_keep_size: "2GB"

  monitoring:
    enablePodMonitor: false

  managed:
    roles:
    - name: grafana
      ensure: present
      login: true
      passwordSecret:
        name: grafana-db-user
    - name: authelia
      ensure: present
      login: true
      passwordSecret:
        name: authelia-db-user
