apiVersion: v1
kind: Secret
metadata:
    name: minio-static-server
    namespace: default
type: Opaque
stringData:
    endpoint: ENC[AES256_GCM,data:8gqKOoHqbu95Y6ZQSSg/KT43Qx9LbQnzAUcEzHZ2EU8=,iv:pIiGwuRKl2ee7cIQ4NAbvRSceGbKCddMy1Cn97C4QHQ=,tag:hocf++PgyDPbBj1jIL6ZGQ==,type:str]
    access-key: ENC[AES256_GCM,data:0K/IrySKcMGdEyx6XwfJ5owuo50=,iv:+fjdYholPO13Ny1H6LZSq9SVITSFrG8oizdjGOC+wHk=,tag:Pu/sMPlXAgxh0+Z+8WdjSw==,type:str]
    secret-key: ENC[AES256_GCM,data:Gr1nYkqvTm9+b/bIaI2TbEZCOlTqHGSE78rZgysKHh1M24tZ4nyCfQ==,iv:BbxiRS7/HULIqcd+KBQ3CJ3KWJsk5WELj8OoKAGVZ74=,tag:DAppIZFP39Be1UEQU9cIXw==,type:str]
    use-ssl: ENC[AES256_GCM,data:hEgz51g=,iv:kOwBiVwccZEZMu0vaQW4PkvIAywt5/b5EJFgIElijLI=,tag:5Vo84SebvbK+82Ipp6YdMg==,type:str]
sops:
    age:
        - recipient: age1uqu8d6qdtcpnkq029znk90wejpdkhdkkgrwcsdenjkq233g9y5vs8fuamq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WWJLNWFCdlZkdVZZM3NW
            T09FbmNIMUpjYWlJdFQrSzUyekI0V2Y2RldnCmJzdWVrenRtNkJ3TEZNamlEUkh6
            NGxUUjIxS0hEMlM3SFRkWjBkbkZQcGsKLS0tIHFlVEw0WHRpZ0h4Nk9sRk1LcXZp
            bWxVK3NvbzEzZnIzMmh4dS96WXFRSEkK1ImGHj+JARkgsiTodYCF79PKe/0f9pkY
            dW4gT9cQ5evOtl0rWqQhc409yqfb0jYGc6H2vycx+Ykbs1gTE0p+4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T20:21:14Z"
    mac: ENC[AES256_GCM,data:gui2cujCx4XUZptTplNfSmW4AFKScrkeg+/pEq2dn6CxaL4ET1y5Z1J1WX3ZlzZ836UNcpo8oldce1B3aJCS3j5c+ji/BCNWZvS2Tu3d5QiPY3AchAW4JTOB9jIIcH6ZJ8SzVxwZKgXHPYNkPdCbCAH1AxZ1VF5T/pFTWkidlj8=,iv:JenRgD6APkqNqUIWdAEJf39za4ZArENmP/3AyhZDEZs=,tag:RaUVDKTDqFZ7jbl5dM5yfQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
