apiVersion: v1
kind: Secret
metadata:
    name: grafana-db
    namespace: grafana
type: Opaque
stringData:
    GF_DATABASE_USER: ENC[AES256_GCM,data:1ZqItlu6wA==,iv:lEDLvqgJIrBGRkuc1qNqinUZxjCTzga3Yqv+XzIc1BE=,tag:YZ9nT780F8zMh2NTCFYrXQ==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:FdVY3GnLctfRZFUQGI8D5w9B8giSWrMxtLxpb+RpZgM2LyjnvhLb10JfeWQ=,iv:aZVDzfoNQBAzaHtmuTCqTzmmKz/XZW0uoHfVwKdz6xU=,tag:d37NJU9VAuukWO2JbhoGag==,type:str]
sops:
    age:
        - recipient: age1uqu8d6qdtcpnkq029znk90wejpdkhdkkgrwcsdenjkq233g9y5vs8fuamq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZjFhb3RadlBPbE9FbU9o
            MVZGSW9oaS9qQ3AvRTZhRU5WVWhsRUpGUlQwCnI4MlY0MFhCak1uKzVjVUlnU0Fp
            dUgvZU4yS1dyYWU5aTQvbkR0MDN2d1kKLS0tIDVXRmlqTVM3TUlweGNMUHB1R3Zx
            d29sQ0Y3Z1hBeXVvVlljdFh2Vnp5cFEKXNVbhov4G471Hmz8DM+BHDlA8Sd0YjSL
            cn5Blpto2+Rfv71EPU3zuDbgs94DbNF3iR5zeSaWbCKjzwkuYDuFCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T15:55:28Z"
    mac: ENC[AES256_GCM,data:7mMurOqIlaGg0whX9nHXF5LogMsQNI0gTweSYCaKb8GYbTDMLSykJWFqm0ZtR+sDSUnGEK/y5J8Saz0qN+YoYZaZbHQ8YHudELc3XBQWnt9jAZ/PwQufd8ZAeSEtZKPrsS74IEthffaRJVaXvpCskD6xrAfF9a8jMek+/0aNu/k=,iv:3TyrpxIJve8UNp/WvfBUWTUEN+yapkoFVxHdgS0V6Vw=,tag:jbsarTxSSRg+5lOKLvlLxw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
