apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: grafana
data:
    admin-user: ENC[AES256_GCM,data:jnRD75Q=,iv:IMUqiw9WTw3AaXMq/hzSpG2g8yFIquYvvf5tj9cYJ6A=,tag:ZNm6HdNe0MukdbcCC2Q9IQ==,type:str]
    admin-password: ENC[AES256_GCM,data:54iYe7bdxjy7bKiSXh6ur9hpP1+WaWktpvEpYgGT1ag=,iv:zLrG9gqDqejXrmaOuThP91McQicPOtLQeGbxy4ml3PY=,tag:6R6tWsYj3m5D9Wa6C3q4PQ==,type:str]
sops:
    age:
        - recipient: age1uqu8d6qdtcpnkq029znk90wejpdkhdkkgrwcsdenjkq233g9y5vs8fuamq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJd2plekNRR0g0UElWaVUy
            N01sRGNpZW1XUms5UXNIS3ZRUTM0L0J0RlVBCmoyNkJWRDBIcCsxWXBwRUFzZVpu
            c25XUldlYWx4MUE4bkZUdHl0QTkrejgKLS0tIHZGOXNDOG5UcmliSmRyVXp0bFZR
            Vm5KSXp2ck11WE9BUEZKNDc3eXl5Z0UKcAQu05RJ4hsG3PSnCJzjC/fmiesrvAv2
            iZQjiw2fWOwa2yrg+rydhTcgsXtuedT1grUcp6oTeasKmTyE1GhMaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T14:58:51Z"
    mac: ENC[AES256_GCM,data:3kuZL6b/i2VbvrEkwgouIDK4j/dHFqUJd8Bil9bvHD/l3qKKOqlwURvLjIEObxOzAWgJoGwR588IG8YSXIPMt88WAUIHGfkIi9XX82jg62I0fxbynCaWLij25XsTwnin7MNYbruj49MBku07C1LhBi4WmPyDo4s4oKeaO268lZQ=,iv:1i7ujLuzbH38vqFzWllYC7b5VBXTaPLjA4hf1JTu/38=,tag:GD/raUGV64DRQWTqc11GCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
