apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: grafana
stringData:
    admin-user: ENC[AES256_GCM,data:Apcx1Ck=,iv:gfQYlvMxk6vBZ7YoJ0+ZUlw+rwkY/WQ416Ul9F//4bY=,tag:C2EYwTOQnvIVq/VdjXWkOg==,type:str]
    admin-password: ENC[AES256_GCM,data:r5oLyoRHtsyGE0AENnzhmZM/YSzjCVHDhJTz5ufBeBU=,iv:5YKwIJEwJtUiQsl6L6wUnL3gVEVorj8urMthDlUPObM=,tag:+meorKsy0Onh/nlI3u2NKA==,type:str]
sops:
    age:
        - recipient: age1uqu8d6qdtcpnkq029znk90wejpdkhdkkgrwcsdenjkq233g9y5vs8fuamq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUklQU0xyZUNvSnlCOHRK
            YkwzUWM2Wm9QaitWUWhJY1oySVdGOVk0V2lRCmNYdGhZZ0ZEaEdia1hKamFSWVVL
            MGd4ZFdGczl4V1dMREplakoyekRMUXcKLS0tIG5Yb0xIaExpU2ljYjJGcmZmN2tB
            c21PY2M4cG5LUkloTk5adEJqVFBVZFkKi+bLwq9VzHcoZGZClHMPwWFEtkS8BmkZ
            MnbWWrfaYL6E143EOyqEFDS8MdHBdslp/2gAE/sqExjsyKmLXRsolg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T15:09:46Z"
    mac: ENC[AES256_GCM,data:QeBspVYY4LjwepngHK9Ppru5PSw1qrrXi2Z7qnkb0MlxICyffTWwGoXgpaDCWvGy8ov8MjuMfKvhRgBMFt8RqYOL1awabNbtoq7IhVtwbttLqZQXTyamxhGe4foWXtNawzdmrkvR6GXba7c5oBxmbSwcojBJyFIZT5iY/rCNiA0=,iv:ZkPHyqHKkbK9gbrcXh7ZclgyKXnCK4S9iT/O5DsxJGQ=,tag:MNaaKghU/Ey2ncoyC5dcbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
