apiVersion: v1
kind: Secret
metadata:
    name: grafana-db-user
    namespace: postgres
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:JoKZ3LDDdg==,iv:bI0OAIg02MeJZC40LzOw/TDr/w4187iKh3wV0JXVzmI=,tag:swWicMTJUvLD9Wy/xcmFYQ==,type:str]
    password: ENC[AES256_GCM,data:NgixjvbuU8lD2krDdzOkUogSGCGotKw3bOj6VKkifiV/DDI1ejZOIJIHjm4=,iv:h/MOU/ac/qsZ55TWiwfO9CfuoHyfevpyVQ1Z0ZzJnQI=,tag:FwQaDLUMD/JZlH1n/hbeFQ==,type:str]
sops:
    age:
        - recipient: age1uqu8d6qdtcpnkq029znk90wejpdkhdkkgrwcsdenjkq233g9y5vs8fuamq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQ0l6MWhPblVTSm0yS2Ns
            ZlEzZFhrb242ZWtGZXdScWdJako2YmxJZ2hBCmpnYmtuRVF0d2x6L0dlVzh1bUI0
            cFN0aDh6YTNJNzdYeFI1U091NXdNaG8KLS0tIHdFMmdCQUlmci9YOFJ4UXk5dnVj
            M2t6VnNydHRQaXlLM2JPUUhUNHBtV3cKFHFXZxCXfS22CmC5WVg1wtDZEjOnHwAg
            1hisc0irhvMjsJE4fB7oNDjhgAd/2/gQJyQXp3X6CYLyq8Wxv1Qhkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T13:23:21Z"
    mac: ENC[AES256_GCM,data:g4yggo57RnSX1w8z2oBWlbuHm18OPIIe6CzV5XpFkmDlhBAgB6OaQ1LoPGEUsp2wdGjQFbfx8OTjpETqshCR3iKDVnJds5jFv5L+2mtH/esii1oE8Bn+B+Q7u+IsMFdKuUqfDIzEb3JB2drrdto0xagNihneU0kyL+tEquLAkzg=,iv:zGYJz2SO2gRNda7HBeuL7vA/BqNTXlTi3nbKJ6dc3tk=,tag:X699IYoQeko0D8bkeCVonQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
