apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mariadb

helmCharts:
  - name: mariadb-operator
    repo: https://helm.mariadb.com/mariadb-operator
    version: 25.10.3
    releaseName: mariadb-operator
    namespace: mariadb
    valuesFile: values.yaml
