apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: valkey-auth
  namespace: valkey
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: valkey-auth
    creationPolicy: Merge
  data:
    - secretKey: admin-pwd
      remoteRef:
        key: valkey-auth/admin-pwd
    - secretKey: authelia-pwd
      remoteRef:
        key: valkey-auth/authelia-pwd
    - secretKey: replicator-pwd
      remoteRef:
        key: valkey-auth/replicator-pwd
