apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: valkey

resources:
- namespace.yaml
- external-secret.yaml

helmCharts:
  - name: valkey
    repo: https://valkey.io/valkey-helm
    version: 0.9.4
    releaseName: valkey
    namespace: valkey
    valuesFile: values.yaml
