apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: palworld-secrets
  namespace: palworld
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: palworld-secrets
    creationPolicy: Owner
  data:
    - secretKey: rconPassword
      remoteRef:
        key: palworld-secrets/rconPassword
    - secretKey: serverPassword
      remoteRef:
        key: palworld-secrets/serverPassword
    - secretKey: playitSecretKey
      remoteRef:
        key: palworld-secrets/playitSecretKey
