apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: palworld

helmCharts:
- name: palworld
  repo: https://twinki14.github.io/palworld-server-chart
  version: 2.7.1
  releaseName: palworld
  namespace: palworld
  valuesFile: values.yaml

resources:
- namespace.yaml
- external-secret.yaml
