---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-secrets
  namespace: authelia
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: authelia-secrets
    creationPolicy: Merge
  data:
    - secretKey: identity_validation.reset_password.jwt.hmac.key
      remoteRef:
        key: authelia-secrets/identity_validation.reset_password.jwt.hmac.key
    - secretKey: session.encryption.key
      remoteRef:
        key: authelia-secrets/session.encryption.key
    - secretKey: storage.encryption.key
      remoteRef:
        key: authelia-secrets/storage.encryption.key
    - secretKey: storage.postgres.password.txt
      remoteRef:
        key: authelia-secrets/storage.postgres.password.txt
    - secretKey: session.redis.password.txt
      remoteRef:
        key: authelia-secrets/session.redis.password.txt
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-users
  namespace: authelia
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: authelia-users
    creationPolicy: Merge
  data:
    - secretKey: users_database.yml
      remoteRef:
        key: authelia-users/users_database.yml
