apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authelia

resources:
  - namespace.yaml

generators:
  - ksops-generator.yaml

helmCharts:
  - name: authelia
    repo: https://charts.authelia.com
    version: 0.11.5
    releaseName: authelia
    namespace: authelia
    valuesFile: values.yaml
