apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-static-server
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: minio-static-server
    creationPolicy: Merge
  data:
    - secretKey: endpoint
      remoteRef:
        key: minio-static-server/endpoint
    - secretKey: access-key
      remoteRef:
        key: minio-static-server/access-key
    - secretKey: secret-key
      remoteRef:
        key: minio-static-server/secret-key
    - secretKey: use-ssl
      remoteRef:
        key: minio-static-server/use-ssl
