apiVersion: v1
kind: Secret
metadata:
    name: valkey-auth
    namespace: valkey
type: Opaque
stringData:
    admin-pwd: ENC[AES256_GCM,data:ix7lI2x0TYvO68Kz+z0JTxMyf9k1D/96IcWxST8JhjonF8DwqsVWphai+HsAiYM7wj1edYhcNhZigpK5ufheyA==,iv:ZxqME0jGzwhjZdV7TS6chulpCabCsVPc+4OPkS9tQf8=,tag:cgkIV357PaPAawv5+SR9PQ==,type:str]
    authelia-pwd: ENC[AES256_GCM,data:d3vv2ZcWlnsKcJay6FCv54Vbp1cu3tGMISgFB/SM7Pga+YPPNAd3iM1NCarNmaIO6HordeINN00saQdTFLcLKQ==,iv:LcYF+bgHmGrs66O5LN18ZAjvynWKYTlLcdRkwcloOQM=,tag:/x030MDFomLQDsH2rZPSxQ==,type:str]
    replicator-pwd: ENC[AES256_GCM,data:M5uNpC5TxSYhX54zDkE8saILUYQYWu0/wls5YeKMbbQoSW4r48mpRbIaOaOg7qXOoEX2ZouSp//HKv/0CpazdA==,iv:/AvpYNYUDb0TdvfD0COVhmneJsosaWGvOAe+6y5qCKo=,tag:2KACsPOxNa81xJu99sdxUA==,type:str]
sops:
    age:
        - recipient: age1uqu8d6qdtcpnkq029znk90wejpdkhdkkgrwcsdenjkq233g9y5vs8fuamq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaE42bmpMWWFSN0ZOTTY0
            Uyt0c28yeE1ZdTNYVTc5dHhOMThDeFpRUkFJCkVOdFphNHBBdm5Ybkp6QTBVT3pt
            cHpMeE51T3Jsck9GRXVGbG1QWU14R28KLS0tIFgzU25qNUxUTlUzMkxTTmwzL2VG
            YnUrUGNRbThCK29rSGlubTJYb3hXMGMKl127vi4hzMoKWPV+McDC6olP0CV7hUJE
            XfLxaSfuofisKjMovddtMt6J/hADhms78SwUCFOsc8UDumDAprt92w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T14:35:41Z"
    mac: ENC[AES256_GCM,data:8M6re8JSFf2SWGQ2xMY7I4Ds1P/7w1mu+fxQGkrTS4egTsR6mS7KAF1XqxX01tD+54cVE1q2R1IVl29kRSSVW9VPPexpbir1NXWBn48yh2XC+pqQqzRCUDqm3CR1BD0vcIRiQjCLP0Ht5EdTk5MDdxnf4pUW8R7KPvAXpKJ6Bwk=,iv:T2wMUm+LHhVd5QqnYFrfOnKDIQeLw2CVUmeZNVEpjkc=,tag:N+lgxUrncgNx1upafdlHzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
