apiVersion: v1
kind: Secret
metadata:
    name: valkey-auth
    namespace: valkey
type: Opaque
stringData:
    admin-pwd: ENC[AES256_GCM,data:ct0MZcI3Ikgk1bOAFU1DLqNuO9+ViKneTfxHoo61iNdUU6idZkBto7AE7yJyYCgmP9mBcvqqvm6zuCc9z7R2WA==,iv:PB1rjhxrwdTTBnDPktgzybF1BYYpKcfQQR4ITZTkWEg=,tag:OlK4+oG94Ksfr91YRWhTQA==,type:str]
    authelia-pwd: ENC[AES256_GCM,data:0v5zKLehQaFMUbIm2bl4y5c+MKB6v0zV4el0MlXX9AgqupPj9xv2PMstIMQzzI4KT9qDZiF2zJFWg1iGnH0Ymg==,iv:9jYaAD5qW7yOE3XKsIwp27iNVptLwX+8N3ALhiH2nxQ=,tag:1TQ4v/G7/Ud5TaDDyAninA==,type:str]
    replicator-pwd: ENC[AES256_GCM,data:IXe9E7eL6z3a9cQ5OaniycfIJg1Ki9hBeyvhzPo4R2DT+eHVLN7nJjscT14Hp2EuEhtMYY1VhIuA4BzoncSS/w==,iv:E559uO3gDZS3RY0jskIji2En/eOdjRhPT2ZHhPDcerM=,tag:BfnYyaOivJwYG3nEGaUfVg==,type:str]
sops:
    age:
        - recipient: age1uqu8d6qdtcpnkq029znk90wejpdkhdkkgrwcsdenjkq233g9y5vs8fuamq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeW5SMlk3TkUvd0o5WUg3
            MWV3cUd1NENFbkh5L1FmczRYWXZMQkdsblFZCmNPVXQvbnV4WWZpR2dNOHNLbXhQ
            cldUMTRtTGJoNlgzbEJrTXR2WnRadUEKLS0tIGQ3TGVZM3VQbXNBUm42Q01qU28x
            QzhuMENmcW5vVTg2Y3N1c2VsRG80WG8KsYMycvqqLadGFJ2S+drBQz+YOjbMq6Ad
            SQDQzfs8rYvZCctkaVmtP0vvG1l+YWV+wyqA0aRsbfazNWCo4sB6Bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T14:33:18Z"
    mac: ENC[AES256_GCM,data:AUb8oU0qiVBuRsHXNs3e0feFwEn/hVatx+PBz8yqhgnqLSA+faWCt+MCRZcnUQAXiADdwhp/J14/6rYdcHh2iaCJc064bxnP3kYNAiMroldaQDbgEBmKO19ZXuNNdq8oo8ZDn+v2/4ulu8CIHXVPcLUbInjvcdberMYUGpEbn8s=,iv:hWAiR1OCTZhywhh1ymHQg6vTLJl6kk2DZ6ZwXvKEiSk=,tag:/tZ0EbeBtIHOa7E+y1PXgg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
