apiVersion: v1
kind: Secret
metadata:
    name: authelia-users
    namespace: authelia
type: Opaque
stringData:
    users_database.yml: ENC[AES256_GCM,data:tTgoTsydaNTEHc8fkTmIhAKp0Uh1N1QmzQF3RyMU6YAKU0qI2ByBiAODA289I+W1nVCZAZOwVKnGQhkAwH+6bRtrPE1ki3ty1MOjaptsMKm6W+dbPjhqa/WbBn+tId+ZEN1UrPjxOUasiS4lqdOtOLNCzgk0/K+u7ALsi2qJucV3oOKUTKPzAQ+Awx6XKitcw9JmuE0WdxqtiiWqRK3mAoigE3ifssgmjr4ViJvUb5M6eh0hqbF2DvQ+0YFyqpxQY4dn07pykFjOh+jquyFOnH5SX7TkppSlT7tUMo41iyX3ReOQtnLQekyfoN9xBSqOWZcXjD4+EVCFpyWg5FWyTB1U,iv:QUfLEN0Prrkh4cM5VYJFHvJwcGmWEzQBtWLmvqmdEig=,tag:rG9/0GoT4ru5/b+S93iNKA==,type:str]
sops:
    age:
        - recipient: age1uqu8d6qdtcpnkq029znk90wejpdkhdkkgrwcsdenjkq233g9y5vs8fuamq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTis1cjMyc0RmdmR0MUdt
            bFJFQ3JnNHlCOEQxQ1FVZ0RJNVZkdEdXQW5FCkdDR2prbjZhOU1UMHZ5alV1dzNP
            dVFiZWRpRzA0cnIrVFE2bzlGVlBMZWMKLS0tIDJmSXFNS1lpTnByUXdOWVUybTdT
            WDNrcFQydWdqVStVdURqM2RMTGQyTkkK9c9nKr0vm0SfuXJpItg8Ak1lZTrMt74X
            Rav805vmS0fYSdJ3ITKwEUEA1areiNZIbdGrpPf4EXr7YotR+UXwKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T06:11:29Z"
    mac: ENC[AES256_GCM,data:mO5jzUEaB5AwPHl6PP3KQouTDdVcGpRyT7QopVNIZn/CaA6EwLUfB7l/kQ1yETf6HMDqsGBTK0+c9CbB59cV8MUqnklRJikdSIQ+rJtr2gMSqMvJIgENT/B8RkkDk+thTfk7OShknyyxyPTxlHII/HVjcw6GqkZmSAlUpGxu3sU=,iv:U+n6iy6qv2ZQT3A277lorPMKIF6nDKoxKhs6GeJ+5kw=,tag:HObmWVmc4o5Ov/S9lq2F6g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
