apiVersion: v1
kind: Secret
metadata:
    name: authelia-secrets
    namespace: authelia
type: Opaque
stringData:
    identity_validation.reset_password.jwt.hmac.key: ENC[AES256_GCM,data:ZOPE9AZpvOc+JotsqiSEDpslxjK+rYBs+RkL8RlXkIkMh9ifKLKWVkQSqYkRhy4k1eWjf6d4nD5X2/TiKioF2w==,iv:I7pkaHAi2peHpsn3MJP5e7PUT5z4DhyQU/2ixCOm/SA=,tag:/wtAUt+G0mj79nNoy7K9og==,type:str]
    session.encryption.key: ENC[AES256_GCM,data:bIvColPqI+inau32n40183usqI3fnlkxYk/HPQiJ+yYlLdyk0S1L5G6b5085DOxVupDh9z+F4LF87WEfFhDkEw==,iv:wWgL/EhNUr95bf0j3st6t1I7puAUL6o6hopIeMamvGU=,tag:IOJ3H2z/C3i75MjN/bHcYw==,type:str]
    storage.encryption.key: ENC[AES256_GCM,data:fOlCJg2SwrAnAGdyM7scl3uQXdsIYcWEnBI05LaMDs4aptg2GMDWMYy6xwYO6VK/kwxCeUon49N7PQuwQeBlPw==,iv:aKfK8YgQC5/k8mQ9G3Mdz0TqHTws8x77kgexia1cGm8=,tag:CFqOwBx5mtEhj0VKYs7uLw==,type:str]
    storage.postgres.password.txt: ENC[AES256_GCM,data:68+UwVggASsHvWzG6eDeFId1SPzmtjf5sDiZThr/M8TMsCoq6SNfagXGtcjkrtcIvZ50vUK6pRT5Fr75W6dohA==,iv:JCAt7mScysFruneXst/NJVTLQt8RwrVEXJiOuAt/yXs=,tag:dor4Mkzy5P3zV22kNm5PFg==,type:str]
    session.redis.password.txt: ENC[AES256_GCM,data:Y1T0p22QZF6L4mjYyeZRB6478JL/cv6T6xNEAG23C+yN36BwbLy+6LXOIrcNSQuIOk4W5zD/OPZSyEN6fs+h4g==,iv:f7uR8eIZZf9n3Vqiecn3c78JSUxM8C7H7NMyUW3HeV8=,tag:rW/fzf8EPWgLeGoibAoehQ==,type:str]
sops:
    age:
        - recipient: age1uqu8d6qdtcpnkq029znk90wejpdkhdkkgrwcsdenjkq233g9y5vs8fuamq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZG5qWHpZTTJYWFJwclJu
            Mk9reU1LaTJrQy9lMEhOdUJLVHBhcWlwc0hFCmNwa1ZWQkl1V0ZUdjlSM3dYZGpk
            MGw2NmhQaWFLdFNqa2ZWOUVXaHM2SDAKLS0tIFB3MjdFbE9VQzg2MnorV0RDOTlT
            bDA5cHJxZDVvc0kvQXRFWnI3Z3VXVzAKpJRScuorRFjz9CHclmThrPk8ozJST3QO
            yzd30rD+leBSK9RsC7G0GSuCODUo2ua3uPqqcv9byj+3gZg6XFQEPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T04:44:31Z"
    mac: ENC[AES256_GCM,data:auohb1mFF3Ch6hn2mTcOtNSvipIrmyFPWhmpp3N+QTPjrOtx3KIJ/6nQnfcjEcl7GDY57Ahqo2hd77C4Mfn8EvHvuSDlFEi8LydQPnzIFaE6oTfPdkpOrYIQ/44FrgsHVHdfzY2QuxZXDOcljx9+Ram2QALrCo6eNNW7li8+DAk=,iv:lMn++5QVoLEh4/q/19zSh6P78OPfriJQ6R6VwJjMPfU=,tag:4x65ZnyB23gfIflkhEWnvQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
