apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:DwCieQWaa/W0sp+ew7Tkpfzkas4K05725UVq57uKmPMPzhKYwHijWYMlXxHlsgHvuIP5YCd7uXVRa++V4mS4poUUq4+EnYru/Cryqm/3pjO/9wYr0WX6FBRhkwB77kch3eqlN92QZDTWAzkEx4GQXyjAOWuqjMtOsAJcIYTFFqnx1U1tQJmSdwdRbyHdJZp9jXSrCBkBjFYQJjukSp8CaqJF8jllGmx8D+0QBJVgySnfz5xumBSBTcV1wZQgQTlag1F/80rnA1zw6rmzpvDWlmDM38IRqNMRxERfnelaQpxLooZ4+ObTaq/+KNI=,iv:KqBwi4h362q0RJynmvTNrE87Ov1ZOgq76lLkM36Oy3Y=,tag:+UJvRioq68VmwUKAu/s/+g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
    namespace: cloudflared
sops:
    age:
        - recipient: age1uqu8d6qdtcpnkq029znk90wejpdkhdkkgrwcsdenjkq233g9y5vs8fuamq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTlhhL0pwczNBZkoveW80
            a0dFQllVYmtaeEZxVzFSa0xrNVArY0ExcEY0Clp2WU05WXhDK0VaL0c4LzhCdVMy
            Uk53UDAxcjMvYkV6NmtLNWpHQktTNk0KLS0tIGFCQ2RHaWtoM3Jza3lFaXkvcE12
            VUE2V0dkeUo3SkJvZGhLeVVrVmFtd1UKmHDhtkUhQDhqjNZKUGttN5zdcbB+HSPM
            SWfJhaw9KvYf4NZLq9gt95KhUW+r0O8e3jDpiRCihIM/NtZ5RKY2bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T14:03:15Z"
    mac: ENC[AES256_GCM,data:WzGYQY9Yxs5btHjoqTELQSRMGzLFEDVW0VrN8ylwKQ0kv74g+N+DY0qsuDOql2LGxLvUuBvZLYmYtm3rlx8fyQpqCo/4JZAB2VcAPKnsD6xrjCznMHKfubIgDYSZyY26KU5QWqatl8RcDMXTzKpGB1yw10zQBu+qp8/eMNvCuT0=,iv:tvf1AQJgTXll66pJecj0Kxljn4h7kzKEtY5OiWrHIBA=,tag:U6K/ZCe4ZLpAhG46VZgDfg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
