configs:
  cm:
    url: https://argocd.yadon3141.com
    kustomize.buildOptions: "--enable-helm"
  params:
    controller.diff.server.side: "true"

redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
  extraArgs:
    - --insecure

repoServer:
  enabled: true
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4

applicationSet:
  replicas: 2
