configs:
  cm:
    url: https://argocd.yadon3141.com
    kustomize.buildOptions: "--enable-helm"
    resource.customizations.ignoreDifferences.external-secrets.io_ExternalSecret: |
      jqPathExpressions:
        - '.spec.data[].remoteRef.conversionStrategy'
        - '.spec.data[].remoteRef.decodingStrategy'
        - '.spec.data[].remoteRef.metadataPolicy'
        - '.spec.target.deletionPolicy'

repoServer:
  enabled: true
  replicas: 2

server:
  extraArgs:
    - --insecure
