---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-admin-password
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: password
    creationPolicy: Owner
  data:
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        key: harbor-admin-password/HARBOR_ADMIN_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-secret-key
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: secret-key
    creationPolicy: Owner
  data:
    - secretKey: secretKey
      remoteRef:
        key: harbor-secret-key/secretKey
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-storage
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: storage
    creationPolicy: Owner
  data:
    - secretKey: REGISTRY_STORAGE_S3_ACCESSKEY
      remoteRef:
        key: harbor-storage/REGISTRY_STORAGE_S3_ACCESSKEY
    - secretKey: REGISTRY_STORAGE_S3_SECRETKEY
      remoteRef:
        key: harbor-storage/REGISTRY_STORAGE_S3_SECRETKEY
