apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-credentials
    namespace: cloudflared
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:+lJd2ZJ9rPu9U53f/Xt5FQUU6VGCLwpPGrNo8J3LT9rU9+qkWzH5sA==,iv:rB3zza94tN/+Nyc0FAU3rZlMqgZ8D7WmlQreX4fTMn0=,tag:4sPxKtzl70deilwWCh4kyQ==,type:str]
    zone-id: ENC[AES256_GCM,data:DOi8OCn0NtOWBXq5HCqnBIM6grdzer7ygIjUeybkqhI=,iv:vNIUQwVOAKY+GLNNYqziHN8YNHHWAr3626ddP2j7IlE=,tag:bBo4oBB1oMU3gNblyuWRmg==,type:str]
sops:
    age:
        - recipient: age1uqu8d6qdtcpnkq029znk90wejpdkhdkkgrwcsdenjkq233g9y5vs8fuamq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2eVk1MEdQTkZPVlFNL3Nm
            QWNSQ1FEbUlRUzVkZmU4eU1PODBCN3hpakNBCkJ6bTlxaU5RYnFmc0YrV0JWa1BK
            L1ZIN3ZBN3dMZUJFdTdRNm1vMyt5eUUKLS0tIGRlMFk0NHpwVEczaXdMSTFYYzly
            bDl1Nm03bHAyTER2OEJaSDNuSU4zRlkKIT+PNk+y+260KUxsVP9DmpJpXANJolRd
            fGpshrocTfj8b0NIKhwFTRqPJAwtkUis+hc6jA9kZchz/sRJmsjExg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T17:32:32Z"
    mac: ENC[AES256_GCM,data:LRmPHmhMoVNVuAaaEKVdNiLjkkPYHdv7BjxndbxwU/KCmhgBUUrgkneK794kWLRpUAz5OV9K5p+2MDramNvo+cGocA5F82N6PMwTTXs8CkaKAVVNU6idK2OQgw3JsWoSHbf8TYHJ/NW+IoNqUYVmNMCcew2fJOrfjqEhRAcN9Js=,iv:QiqroJKw9X4Sn57p1FRfqgexKJAFCl4d9cUCVlLMv4k=,tag:aNfd7vGSmK7CVuFSF+3Sbw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
