apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-credentials
    namespace: cloudflared
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:bsv2a9n848psa7o/yEkQZkX/c1ve+qzgPDNLe5pSAZ8DXgMcKiPaWeerf/UjCjxjAiQSHVQ=,iv:bTBPweWOGy6STcBzJ6cMQxp1tAGZWTm60TQpAqHlyeQ=,tag:IJA1z4SlF/JnJIqER7+7WQ==,type:str]
    zone-id: ENC[AES256_GCM,data:4o0nL2L6yZ7gkIcUSkmSREatdbMjVB2tUXPRAVoDrDo=,iv:GrBPObn9UM50PQSZB2dMG3V9WBJdhTdfBPwLjHsLV/E=,tag:l/ajQo97VO4CUsXa4qguXA==,type:str]
sops:
    age:
        - recipient: age1uqu8d6qdtcpnkq029znk90wejpdkhdkkgrwcsdenjkq233g9y5vs8fuamq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMVpjSjZsSjFlMHczb0FJ
            NEVHSndGbFdDVVppeFJubzlURG1uekF3UDNjClFQSzdVaWEyUUlOaDh6bTdkRnB0
            cW91WDNVenFVTm9jcGJZREZqdnBOTm8KLS0tIDdSTHQxNjY2aGg0RlVTRTJscE1W
            ZTkxaFlNa0YxNithMlBSQWUrWURLL0UKsQA3V8FwPEjtFkitsv7Y7fspg7jQ9h/r
            N5Ej5mOST+U8ZU+E/zg9CUAZ4dYxCYw+RFTxAQE/9NBmmTv5KqjaZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T17:09:14Z"
    mac: ENC[AES256_GCM,data:m3fVmwXEFmoEBriM6khPBCDRzMl/VJFU40HxBnWHWOvaqPth4DCNkQB0yndtV0POirVa8hl8qxgesOI7r+G0V0Mh8nxUa9pml0cyg4pjf44nExh5NDPk/XDrdEN3brk6Jn/QB16RKZY8/38Tn+UWna8DmGNab+IWO0DNyHBCTYI=,iv:5Ja4WHg6Bbvd4l3zW7HdZWBg6NJBymr5GKwaJaRotQU=,tag:imyghLdMrs7sz196VpHklA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
