apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-credentials
    namespace: cloudflared
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:Pw3UIvfFS7NNJjWfeuc8ww+J6JY0TZ9V0DNAjgSvxg7iuya8mkedRA==,iv:QdpH3mGgE11t/5DJUC5QSWtePybzBX0qKwH3WlAgAvU=,tag:Isjc9T0O5C2GRYB/M7cqZg==,type:str]
    zone-id: ENC[AES256_GCM,data:/AFm3TTf/GYcM4X9r8Z7cJV/YpheDlMpc/h6gyVmSaQ=,iv:HzehV7Cwx2awied6APIab59hPyU5/i2GLDLZyP12BFI=,tag:TjKZDntwtWdPpICL5K2bPA==,type:str]
sops:
    age:
        - recipient: age1uqu8d6qdtcpnkq029znk90wejpdkhdkkgrwcsdenjkq233g9y5vs8fuamq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSDB3K1NjQ3RSYm1qdkt0
            cFdUSG9QeU5IUy94NVJ4cTU3bE50RVljN2tBCmxhZ2plMGZyS056MmhtTFRIRmUw
            dURISmw2OFZNRjRJTnB6Mmo1QVI0RWMKLS0tIHhobXFjMHFzUlVtbXVyb2lmRElP
            cXBRbmxQZDZ1QUlOVmJ3dVJUR1p0cDgKrqzFlx+3N6a+7DiHYHpjhtsVX0u7m3dJ
            +Yc0QytW06xWXvf0H+rdBd5GY9dq7oAeLOKF1ZmSdHBAbwC3QOybwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T02:27:59Z"
    mac: ENC[AES256_GCM,data:nd8Qp/xBDJYF4Lr76D8AU2VJ0esexTefzX9cXO/551blv5fRJIIZr77Eg/jtxjsGMKRSdiuy4xckyXdTjaPkyaYKyYfDcPOJnH50qTbjhQKWLi6qmWSAlxJr3bxBSrK6yLgmoTCPRryQUVTJUS0tweiY7ISFO2pGLoTMHMik+lQ=,iv:FoQidIJvz72BOZ6hZgUGwlQkqlK6+oWKv58XdzBdLB0=,tag:HwzIgcanDuvvPogFYhrnRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
