apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: storage-configuration
  namespace: minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: storage-configuration
    creationPolicy: Owner
  data:
    - secretKey: config.env
      remoteRef:
        key: minio-storage-configuration/config.env
