apiVersion: v1
kind: Secret
metadata:
    name: storage-configuration
    namespace: minio
type: Opaque
stringData:
    config.env: ENC[AES256_GCM,data:bH4HdAQg+VpkzTajQjlVunnRMvEVL99mbmhVGva5BRzkX1Iq+AUmhZdFEYBPZVITTWm5QTHEI/99pwzPvFklOYwG4nsUxO/FTgVddu0WwbL/hCtm1ij/ssACGSUQHsMSML04BEtCYtT26CNoelaQ8/KVIQNz+sRtOrDE2KNICTlybw8Mxg/iuLIfaJclGId4S6yqar3bqJQ+,iv:CvLRrSMsAFPfPFHs2QNEQHW2Qbrkv5q+S30KeC4T/Ow=,tag:ky/2ViG8AtIEA/NFUrxDqg==,type:str]
sops:
    age:
        - recipient: age1uqu8d6qdtcpnkq029znk90wejpdkhdkkgrwcsdenjkq233g9y5vs8fuamq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3OHJxclpFeEt6Vm1ZWDRP
            eUtEc01sKzhwRlk5Z2FXSG5nVkMvV0RBc0JRCm5DWTVEZHU0eldKV3B5SkdFWWZt
            UWtGNFY3cUlWdXVtamgxTytpQVBVQmsKLS0tIEl5OHBUdE5IWmNBUmJBL2RFZFhm
            ODI0MHovY1Jzdkx3NitLWld2QXNkdk0KEOltt4wH2N85tUEbzdKYM71cwwvMQJei
            514lgdsAjfh6mYtg63dRb5dJJjvaoC7cIbCNCm7Kld7GX9LvHNcReQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T10:34:31Z"
    mac: ENC[AES256_GCM,data:ZlB1dNzjAFnzg4RfQ1TrbZHrPtlA/AB1n1UNE1lvS7JIYta3abF4jGx2HkSXnHiiN6sTTx5WepH/BKc7aWFk1qZ3gIP4ll6JWKack1Sv4cxp/5+DKy7biZ9G018Mq7cLWPP1c2JrdGfEFWqLMxvIgJ8g5rjmxyyOC0wWj7x8Wa8=,iv:/1OZkY8AuJH2TTzNPAUJYCcviLwPUULGYlXjC/cA7Ns=,tag:RfQMcr0yH1T/CBU1SFYqrA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
