apiVersion: v1
kind: Secret
metadata:
    name: authelia-db-user
    namespace: postgres
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:TLkDUtF1Tbc=,iv:mf1zBEMlFRcxVvtjUiEJRG89zeSn/07XHz/aAzo06b4=,tag:yiTQvN7cfAo43N68ZpOwaw==,type:str]
    password: ENC[AES256_GCM,data:xdMc19nCFuOJVcPDJ5thn6/l/+nhLXZuUvHl2TTHE58Mu2lXmQlWcI7Y81BvmaXA7tnCZl68fpo0yrhe6xc7/w==,iv:z9n1y+ILObeZjP6Sqcl2lxi7nHCHcJHfCEEn7EuxxoQ=,tag:Hv50uh/Uy1Z0Vu3KV7JaCA==,type:str]
sops:
    age:
        - recipient: age1uqu8d6qdtcpnkq029znk90wejpdkhdkkgrwcsdenjkq233g9y5vs8fuamq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwM3NDUFBHWHJ0YXRRNlI5
            emdvUzRxQTBBb3VnQ0FGUE1zRFplZG5lZ2prCnhhbEZ0Y3Ztdm9VNGpuN2VCWTll
            WVArSG9BYUFOK2JkRFlKNk5pd2J1M1kKLS0tIGVrZWdwREZHRkZvakFJRVBHeEQy
            RGE1S2RpL0g4SmdDQkVza2JsRThvUmcKSaGPv9kRl8P88YreVxUWYuqInjbbSk02
            G7GDs4LciW9aP+GlBZUFbAAqVqgbtxxjaG7EzrYBknUSkjkjjwqWxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T04:43:43Z"
    mac: ENC[AES256_GCM,data:9axKT6Lecbfx6RlC0uCoR9NcaSijqTekANWOrGgYhAmvm6VuCH7CjSytSMuRoX9Sp+rXpEh3Icq2gvHcyMMurFOychUmCeIP9efNKoThOemQ/CAsGCgriGHyvgncqJ1p4VR8mlYtOgLyzP+1kLCo8S7R3RvQyXd5qzq/XqAy5As=,iv:YxDf3N7TcH7KudxBeWaYTeiTvmGj9gRe6Hf2ccEg9F8=,tag:Sni48KUs5PUYcTKz+L88WA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
